# Generated by Django 6.0.4 on 2026-04-21 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='学院名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='学院代码')),
                ('description', models.TextField(blank=True, verbose_name='学院简介')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '学院',
                'verbose_name_plural': '学院',
                'db_table': 'college',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DormitoryBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='楼栋名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='楼栋代码')),
                ('floor_count', models.PositiveIntegerField(verbose_name='楼层数')),
                ('total_rooms', models.PositiveIntegerField(verbose_name='总房间数')),
                ('available_rooms', models.PositiveIntegerField(verbose_name='可用房间数')),
                ('gender_restriction', models.CharField(choices=[('male', '男'), ('female', '女'), ('mixed', '混合')], default='mixed', max_length=10, verbose_name='性别限制')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '宿舍楼栋',
                'verbose_name_plural': '宿舍楼栋',
                'db_table': 'dormitory_building',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'system_config',
            },
        ),
        migrations.CreateModel(
            name='DormitoryRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, verbose_name='房间号')),
                ('floor', models.PositiveIntegerField(verbose_name='楼层')),
                ('capacity', models.PositiveIntegerField(default=4, verbose_name='床位容量')),
                ('current_occupancy', models.PositiveIntegerField(default=0, verbose_name='当前入住人数')),
                ('room_type', models.CharField(choices=[('standard', '标准间'), ('upgrade', '升级间')], default='standard', max_length=50, verbose_name='房间类型')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='住宿费')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='welcome_app.dormitorybuilding', verbose_name='楼栋')),
            ],
            options={
                'verbose_name': '宿舍房间',
                'verbose_name_plural': '宿舍房间',
                'db_table': 'dormitory_room',
                'ordering': ['building', 'room_number'],
                'unique_together': {('building', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='问题')),
                ('answer', models.TextField(verbose_name='答案')),
                ('category', models.CharField(choices=[('admission', '报到流程'), ('payment', '缴费标准'), ('dormitory', '宿舍分配'), ('facility', '设施使用'), ('transportation', '交通指南'), ('other', '其他')], max_length=20, verbose_name='分类')),
                ('keywords', models.CharField(blank=True, max_length=500, verbose_name='关键词(逗号分隔)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='查看次数')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='有帮助次数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '知识库',
                'verbose_name_plural': '知识库',
                'db_table': 'knowledge_base',
                'ordering': ['-view_count'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='knowledge_b_categor_2c991d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='专业名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='专业代码')),
                ('description', models.TextField(blank=True, verbose_name='专业简介')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='welcome_app.college', verbose_name='所属学院')),
            ],
            options={
                'verbose_name': '专业',
                'verbose_name_plural': '专业',
                'db_table': 'major',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('priority', models.CharField(choices=[('high', '高'), ('normal', '普通'), ('low', '低')], default='normal', max_length=20, verbose_name='优先级')),
                ('target_audience', models.CharField(choices=[('all', '全体'), ('college', '按学院'), ('major', '按专业')], default='all', max_length=50, verbose_name='目标受众')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='welcome_app.college', verbose_name='目标学院')),
                ('target_major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='welcome_app.major', verbose_name='目标专业')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'db_table': 'announcement',
                'ordering': ['-priority', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证号')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('class_name', models.CharField(blank=True, max_length=50, verbose_name='班级')),
                ('origin_province', models.CharField(max_length=50, verbose_name='生源省份')),
                ('origin_city', models.CharField(blank=True, max_length=50, verbose_name='生源城市')),
                ('high_school', models.CharField(blank=True, max_length=100, verbose_name='毕业高中')),
                ('status', models.CharField(choices=[('pending', '待报到'), ('checked_in', '已报到'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='报到状态')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='报到时间')),
                ('dynamic_code', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='动态核验码')),
                ('dynamic_code_expires', models.DateTimeField(blank=True, null=True, verbose_name='核验码过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='welcome_app.major', verbose_name='专业')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'db_table': 'student',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('tuition', '学费'), ('accommodation', '住宿费'), ('material', '教材费'), ('other', '其他')], max_length=20, verbose_name='缴费类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('failed', '支付失败'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='缴费状态')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='支付方式')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='交易流水号')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='welcome_app.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '缴费记录',
                'verbose_name_plural': '缴费记录',
                'db_table': 'payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='问题')),
                ('answer', models.TextField(blank=True, verbose_name='答案')),
                ('is_answered', models.BooleanField(default=False, verbose_name='是否已回答')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='回答时间')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='welcome_app.student', verbose_name='提问学生')),
            ],
            options={
                'verbose_name': '常见问题',
                'verbose_name_plural': '常见问题',
                'db_table': 'faq',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DormitoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.PositiveIntegerField(verbose_name='床位号')),
                ('assignment_date', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('status', models.CharField(choices=[('assigned', '已分配'), ('checked_in', '已入住'), ('cancelled', '已取消')], default='assigned', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='welcome_app.dormitoryroom', verbose_name='分配房间')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dormitory_assignment', to='welcome_app.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '宿舍分配',
                'verbose_name_plural': '宿舍分配',
                'db_table': 'dormitory_assignment',
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_method', models.CharField(choices=[('manual', '人工核验'), ('qrcode', '扫码核验')], max_length=20, verbose_name='报到方式')),
                ('location', models.CharField(max_length=100, verbose_name='报到地点')),
                ('operator', models.CharField(max_length=50, verbose_name='操作人')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='报到时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_records', to='welcome_app.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '报到记录',
                'verbose_name_plural': '报到记录',
                'db_table': 'check_in',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status', 'major'], name='student_status_f79191_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['origin_province'], name='student_origin__bd6f7f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'status'], name='payment_student_bda522_idx'),
        ),
    ]
